language: php

php:
  - "7.4"
  - "8.0"

before_script:
  - composer install
  - mkdir -p build/logs

script:
  - cd $TRAVIS_BUILD_DIR;
  - vendor/bin/phpunit --configuration tests/phpunit.xml
  - vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - pwd
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/coverage.clover
  - php vendor/bin/coveralls -v
