language: php

php:
  - "7.3"
  - "8.0"

before_script:
  - composer install
  - mkdir -p build/logs

script:
  - cd $TRAVIS_BUILD_DIR;
  - XDEBUG_MODE=coverage vendor/bin/phpunit --configuration tests/phpunit.xml

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - pwd
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
  - php vendor/bin/php-coveralls -v
