language: php

php:
  - "7.4"
  - "8.0"

before_script:
  - composer install
  - mkdir -p build/logs

script:
  - cd $TRAVIS_BUILD_DIR;
  - vendor/bin/phpunit --configuration tests/phpunit.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
